# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmwasm/wasm/v1/authz.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63osmwasm/wasm/v1/authz.proto\x12\x10\x63osmwasm.wasm.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x19google/protobuf/any.proto\"j\n\x1e\x43ontractExecutionAuthorization\x12\x35\n\x06grants\x18\x01 \x03(\x0b\x32\x1f.cosmwasm.wasm.v1.ContractGrantB\x04\xc8\xde\x1f\x00:\x11\xca\xb4-\rAuthorization\"j\n\x1e\x43ontractMigrationAuthorization\x12\x35\n\x06grants\x18\x01 \x03(\x0b\x32\x1f.cosmwasm.wasm.v1.ContractGrantB\x04\xc8\xde\x1f\x00:\x11\xca\xb4-\rAuthorization\"\x9f\x01\n\rContractGrant\x12\x10\n\x08\x63ontract\x18\x01 \x01(\t\x12<\n\x05limit\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x17\xca\xb4-\x13\x43ontractAuthzLimitX\x12>\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB\x18\xca\xb4-\x14\x43ontractAuthzFilterX\";\n\rMaxCallsLimit\x12\x11\n\tremaining\x18\x01 \x01(\x04:\x17\xca\xb4-\x13\x43ontractAuthzLimitX\"\x86\x01\n\rMaxFundsLimit\x12\\\n\x07\x61mounts\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB0\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins:\x17\xca\xb4-\x13\x43ontractAuthzLimitX\"\x9f\x01\n\rCombinedLimit\x12\x17\n\x0f\x63\x61lls_remaining\x18\x01 \x01(\x04\x12\\\n\x07\x61mounts\x18\x02 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB0\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins:\x17\xca\xb4-\x13\x43ontractAuthzLimitX\"2\n\x16\x41llowAllMessagesFilter:\x18\xca\xb4-\x14\x43ontractAuthzFilterX\"C\n\x19\x41\x63\x63\x65ptedMessageKeysFilter\x12\x0c\n\x04keys\x18\x01 \x03(\t:\x18\xca\xb4-\x14\x43ontractAuthzFilterX\"\\\n\x16\x41\x63\x63\x65ptedMessagesFilter\x12(\n\x08messages\x18\x01 \x03(\x0c\x42\x16\xfa\xde\x1f\x12RawContractMessage:\x18\xca\xb4-\x14\x43ontractAuthzFilterXB,Z&github.com/CosmWasm/wasmd/x/wasm/types\xc8\xe1\x1e\x00\x62\x06proto3')



_CONTRACTEXECUTIONAUTHORIZATION = DESCRIPTOR.message_types_by_name['ContractExecutionAuthorization']
_CONTRACTMIGRATIONAUTHORIZATION = DESCRIPTOR.message_types_by_name['ContractMigrationAuthorization']
_CONTRACTGRANT = DESCRIPTOR.message_types_by_name['ContractGrant']
_MAXCALLSLIMIT = DESCRIPTOR.message_types_by_name['MaxCallsLimit']
_MAXFUNDSLIMIT = DESCRIPTOR.message_types_by_name['MaxFundsLimit']
_COMBINEDLIMIT = DESCRIPTOR.message_types_by_name['CombinedLimit']
_ALLOWALLMESSAGESFILTER = DESCRIPTOR.message_types_by_name['AllowAllMessagesFilter']
_ACCEPTEDMESSAGEKEYSFILTER = DESCRIPTOR.message_types_by_name['AcceptedMessageKeysFilter']
_ACCEPTEDMESSAGESFILTER = DESCRIPTOR.message_types_by_name['AcceptedMessagesFilter']
ContractExecutionAuthorization = _reflection.GeneratedProtocolMessageType('ContractExecutionAuthorization', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTEXECUTIONAUTHORIZATION,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.ContractExecutionAuthorization)
  })
_sym_db.RegisterMessage(ContractExecutionAuthorization)

ContractMigrationAuthorization = _reflection.GeneratedProtocolMessageType('ContractMigrationAuthorization', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTMIGRATIONAUTHORIZATION,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.ContractMigrationAuthorization)
  })
_sym_db.RegisterMessage(ContractMigrationAuthorization)

ContractGrant = _reflection.GeneratedProtocolMessageType('ContractGrant', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTGRANT,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.ContractGrant)
  })
_sym_db.RegisterMessage(ContractGrant)

MaxCallsLimit = _reflection.GeneratedProtocolMessageType('MaxCallsLimit', (_message.Message,), {
  'DESCRIPTOR' : _MAXCALLSLIMIT,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.MaxCallsLimit)
  })
_sym_db.RegisterMessage(MaxCallsLimit)

MaxFundsLimit = _reflection.GeneratedProtocolMessageType('MaxFundsLimit', (_message.Message,), {
  'DESCRIPTOR' : _MAXFUNDSLIMIT,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.MaxFundsLimit)
  })
_sym_db.RegisterMessage(MaxFundsLimit)

CombinedLimit = _reflection.GeneratedProtocolMessageType('CombinedLimit', (_message.Message,), {
  'DESCRIPTOR' : _COMBINEDLIMIT,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.CombinedLimit)
  })
_sym_db.RegisterMessage(CombinedLimit)

AllowAllMessagesFilter = _reflection.GeneratedProtocolMessageType('AllowAllMessagesFilter', (_message.Message,), {
  'DESCRIPTOR' : _ALLOWALLMESSAGESFILTER,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.AllowAllMessagesFilter)
  })
_sym_db.RegisterMessage(AllowAllMessagesFilter)

AcceptedMessageKeysFilter = _reflection.GeneratedProtocolMessageType('AcceptedMessageKeysFilter', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTEDMESSAGEKEYSFILTER,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.AcceptedMessageKeysFilter)
  })
_sym_db.RegisterMessage(AcceptedMessageKeysFilter)

AcceptedMessagesFilter = _reflection.GeneratedProtocolMessageType('AcceptedMessagesFilter', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTEDMESSAGESFILTER,
  '__module__' : 'cosmwasm.wasm.v1.authz_pb2'
  # @@protoc_insertion_point(class_scope:cosmwasm.wasm.v1.AcceptedMessagesFilter)
  })
_sym_db.RegisterMessage(AcceptedMessagesFilter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/CosmWasm/wasmd/x/wasm/types\310\341\036\000'
  _CONTRACTEXECUTIONAUTHORIZATION.fields_by_name['grants']._options = None
  _CONTRACTEXECUTIONAUTHORIZATION.fields_by_name['grants']._serialized_options = b'\310\336\037\000'
  _CONTRACTEXECUTIONAUTHORIZATION._options = None
  _CONTRACTEXECUTIONAUTHORIZATION._serialized_options = b'\312\264-\rAuthorization'
  _CONTRACTMIGRATIONAUTHORIZATION.fields_by_name['grants']._options = None
  _CONTRACTMIGRATIONAUTHORIZATION.fields_by_name['grants']._serialized_options = b'\310\336\037\000'
  _CONTRACTMIGRATIONAUTHORIZATION._options = None
  _CONTRACTMIGRATIONAUTHORIZATION._serialized_options = b'\312\264-\rAuthorization'
  _CONTRACTGRANT.fields_by_name['limit']._options = None
  _CONTRACTGRANT.fields_by_name['limit']._serialized_options = b'\312\264-\023ContractAuthzLimitX'
  _CONTRACTGRANT.fields_by_name['filter']._options = None
  _CONTRACTGRANT.fields_by_name['filter']._serialized_options = b'\312\264-\024ContractAuthzFilterX'
  _MAXCALLSLIMIT._options = None
  _MAXCALLSLIMIT._serialized_options = b'\312\264-\023ContractAuthzLimitX'
  _MAXFUNDSLIMIT.fields_by_name['amounts']._options = None
  _MAXFUNDSLIMIT.fields_by_name['amounts']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _MAXFUNDSLIMIT._options = None
  _MAXFUNDSLIMIT._serialized_options = b'\312\264-\023ContractAuthzLimitX'
  _COMBINEDLIMIT.fields_by_name['amounts']._options = None
  _COMBINEDLIMIT.fields_by_name['amounts']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _COMBINEDLIMIT._options = None
  _COMBINEDLIMIT._serialized_options = b'\312\264-\023ContractAuthzLimitX'
  _ALLOWALLMESSAGESFILTER._options = None
  _ALLOWALLMESSAGESFILTER._serialized_options = b'\312\264-\024ContractAuthzFilterX'
  _ACCEPTEDMESSAGEKEYSFILTER._options = None
  _ACCEPTEDMESSAGEKEYSFILTER._serialized_options = b'\312\264-\024ContractAuthzFilterX'
  _ACCEPTEDMESSAGESFILTER.fields_by_name['messages']._options = None
  _ACCEPTEDMESSAGESFILTER.fields_by_name['messages']._serialized_options = b'\372\336\037\022RawContractMessage'
  _ACCEPTEDMESSAGESFILTER._options = None
  _ACCEPTEDMESSAGESFILTER._serialized_options = b'\312\264-\024ContractAuthzFilterX'
  _CONTRACTEXECUTIONAUTHORIZATION._serialized_start=158
  _CONTRACTEXECUTIONAUTHORIZATION._serialized_end=264
  _CONTRACTMIGRATIONAUTHORIZATION._serialized_start=266
  _CONTRACTMIGRATIONAUTHORIZATION._serialized_end=372
  _CONTRACTGRANT._serialized_start=375
  _CONTRACTGRANT._serialized_end=534
  _MAXCALLSLIMIT._serialized_start=536
  _MAXCALLSLIMIT._serialized_end=595
  _MAXFUNDSLIMIT._serialized_start=598
  _MAXFUNDSLIMIT._serialized_end=732
  _COMBINEDLIMIT._serialized_start=735
  _COMBINEDLIMIT._serialized_end=894
  _ALLOWALLMESSAGESFILTER._serialized_start=896
  _ALLOWALLMESSAGESFILTER._serialized_end=946
  _ACCEPTEDMESSAGEKEYSFILTER._serialized_start=948
  _ACCEPTEDMESSAGEKEYSFILTER._serialized_end=1015
  _ACCEPTEDMESSAGESFILTER._serialized_start=1017
  _ACCEPTEDMESSAGESFILTER._serialized_end=1109
# @@protoc_insertion_point(module_scope)
